### ISSUE TITLE
FFT conversion not possible with current FidInfoHS and FidInfoHU

### ISSUE THREAD

**Issue by danielcanueto** [ManonMartin/SOAP-NMR#11]
Hi Manon,

I am a user of your package and I am currently using it to help to develop workflows. I would like to use as examples your Human Serum and Human Urine Metabolome datasets, but it is not possible to do the FFT Conversion as some data is missing from FidInfoHS and FIDInfoHU. If I am not wrong, it is necessary to have nine columns and variables have not all of them, like O1:

Error in getArg(O1, Fid_info, "O1") : 
  impossible to get argument O1 it was not given directly and is not in the info matrix

Could you update these fid_info_files to be able to reproduce the preprocessing with the Human Serum and Human Urine Metabolome files?

Thank you for the help.

ATB

Daniel

**Comment by ManonMartin** [comment]
Hi Daniel,

Thanks for reporting the issues. The problem should be corrected now, note that some dataset names have changed (in particular those in Data_HS_sp and Data_HU_sp).

Best,
Manon
